In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: numpy in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (1.26.4)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import os

print(os.getcwd())

/home/ef6e65df-62fe-4def-b6e2-88db5e7b6923

In [10]:
import os

print(os.listdir())

['.ipynb_checkpoints', '.virtualenvs', '.vimrc', '.bashrc', 'Untitled.ipynb', '.jupyter', '.local', 'Untitled1.ipynb', 'anaconda_projects', '.profile', '.pythonstartup.py', 'untitled.py', 'liner regression.ipynb', 'README.ipynb', '.gitconfig', 'Untitled2.ipynb', '.npm', '.ipython', '.config', '.anaconda', '.cache']

In [12]:
import pandas as pd

trader = pd.read_csv("historical_data.csv")
sentiment = pd.read_csv("fear_greed_index.csv")

print(trader.columns)
print(sentiment.columns)

Index(['Account', 'Coin', 'Execution Price', 'Size Tokens', 'Size USD', 'Side',
       'Timestamp IST', 'Start Position', 'Direction', 'Closed PnL',
       'Transaction Hash', 'Order ID', 'Crossed', 'Fee', 'Trade ID',
       'Timestamp'],
      dtype='object')
Index(['timestamp', 'value', 'classification', 'date'], dtype='object')

/tmp/ipykernel_254/3990438530.py:3: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  trader = pd.read_csv("historical_data.csv")

In [13]:
print("Trader Columns:")
print(trader.columns)

print("\nSentiment Columns:")
print(sentiment.columns)

Trader Columns:
Index(['Account', 'Coin', 'Execution Price', 'Size Tokens', 'Size USD', 'Side',
       'Timestamp IST', 'Start Position', 'Direction', 'Closed PnL',
       'Transaction Hash', 'Order ID', 'Crossed', 'Fee', 'Trade ID',
       'Timestamp'],
      dtype='object')

Sentiment Columns:
Index(['timestamp', 'value', 'classification', 'date'], dtype='object')

In [14]:
trader.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.003055,1.050000e+15,1.730000e+12

In [15]:
sentiment.head()

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [16]:
print("Trader Shape:", trader.shape)
print("Sentiment Shape:", sentiment.shape)

Trader Shape: (88467, 16)
Sentiment Shape: (2644, 4)

In [17]:
trader.isnull().sum()

Account             0
Coin                1
Execution Price     1
Size Tokens         1
Size USD            1
Side                1
Timestamp IST       1
Start Position      1
Direction           1
Closed PnL          1
Transaction Hash    1
Order ID            1
Crossed             1
Fee                 1
Trade ID            1
Timestamp           1
dtype: int64

In [18]:
sentiment.isnull().sum()

timestamp         0
value             0
classification    0
date              0
dtype: int64

In [19]:
trader.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88467 entries, 0 to 88466
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Account           88467 non-null  object
 1   Coin              88466 non-null  object
 2   Execution Price   88466 non-null  float64
 3   Size Tokens       88466 non-null  float64
 4   Size USD          88466 non-null  float64
 5   Side              88466 non-null  object
 6   Timestamp IST     88466 non-null  object
 7   Start Position    88466 non-null  float64
 8   Direction         88466 non-null  object
 9   Closed PnL        88466 non-null  float64
 10  Transaction Hash  88466 non-null  object
 11  Order ID          88466 non-null  float64
 12  Crossed           88466 non-null  object
 13  Fee               88466 non-null  float64
 14  Trade ID          88466 non-null  float64
 15  Timestamp         88466 non-null  float64
dtypes: float64(9), object(7)
memory usage: 10.8+ MB

In [20]:
sentiment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   object
 3   date            2644 non-null   object
dtypes: int64(2), object(2)
memory usage: 82.8+ KB

In [21]:
print(trader.columns)
print(sentiment.columns)

Index(['Account', 'Coin', 'Execution Price', 'Size Tokens', 'Size USD', 'Side',
       'Timestamp IST', 'Start Position', 'Direction', 'Closed PnL',
       'Transaction Hash', 'Order ID', 'Crossed', 'Fee', 'Trade ID',
       'Timestamp'],
      dtype='object')
Index(['timestamp', 'value', 'classification', 'date'], dtype='object')

In [22]:
trader.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.003055,1.050000e+15,1.730000e+12

In [23]:
sentiment.head()

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [24]:
print("Trader Date Range")
print(trader['Timestamp'].min())
print(trader['Timestamp'].max())

print("\nSentiment Date Range")
print(sentiment['date'].min())
print(sentiment['date'].max())

Trader Date Range
1680000000000.0
1750000000000.0

Sentiment Date Range
2018-02-01
2025-05-02

In [25]:
trader['Timestamp'] = pd.to_datetime(
    trader['Timestamp'],
    unit='ms'
)

print(trader['Timestamp'].min())
print(trader['Timestamp'].max())

2023-03-28 10:40:00
2025-06-15 15:06:40

In [26]:
trader['date'] = trader['Timestamp'].dt.date
trader['date'] = pd.to_datetime(trader['date'])

In [27]:
trader[['Timestamp','date']].head()

            Timestamp       date
0 2024-10-27 03:33:20 2024-10-27
1 2024-10-27 03:33:20 2024-10-27
2 2024-10-27 03:33:20 2024-10-27
3 2024-10-27 03:33:20 2024-10-27
4 2024-10-27 03:33:20 2024-10-27

In [28]:
print("Trader:")
print(trader['date'].min())
print(trader['date'].max())

print("\nSentiment:")
print(sentiment['date'].min())
print(sentiment['date'].max())

Trader:
2023-03-28 00:00:00
2025-06-15 00:00:00

Sentiment:
2018-02-01
2025-05-02

In [30]:
merged = pd.merge(
    trader,
    sentiment[['date','classification','value']],
    on='date',
    how='inner'
)

print("Merged Shape:", merged.shape)

ValueError: You are trying to merge on datetime64[ns] and object columns for key 'date'. If you wish to proceed you should use pd.concat

In [31]:
print(trader['date'].dtype)
print(sentiment['date'].dtype)

datetime64[ns]
object

In [32]:
sentiment['date'] = pd.to_datetime(sentiment['date'])

print(sentiment['date'].dtype)

datetime64[ns]

In [33]:
print(trader['date'].dtype)
print(sentiment['date'].dtype)

datetime64[ns]
datetime64[ns]

In [34]:
merged = pd.merge(
    trader,
    sentiment[['date','classification','value']],
    on='date',
    how='inner'
)

print("Merged Shape:", merged.shape)

Merged Shape: (76573, 19)

In [35]:
print("Merged Shape:", merged.shape)

Merged Shape: (76573, 19)

In [36]:
merged.groupby('classification')['Closed PnL'].agg(
    ['count','sum','mean','median']
).sort_values('sum', ascending=False)

                count           sum        mean  median
classification
Fear            55156  4.880959e+06   88.493718     0.0
Greed           11168  1.698047e+06  152.045756     0.0
Neutral          3287  1.823740e+05   55.483432     0.0
Extreme Greed    6962  1.769655e+05   25.418772     0.0

In [37]:
merged['Win'] = merged['Closed PnL'] > 0

win_rate = merged.groupby(
    'classification'
)['Win'].mean()*100

print(win_rate)

classification
Extreme Greed    49.008905
Fear             45.859018
Greed            42.720272
Neutral          31.183450
Name: Win, dtype: float64

In [38]:
top_traders = merged.groupby(
    'Account'
)['Closed PnL'].sum().sort_values(
    ascending=False
)

print(top_traders.head(10))

Account
0xb1231a4a2dd02f2276fa3c5e2a2f3436e6bfed23    2.040922e+06
0x083384f897ee0f19899168e3b1bec365f52a9012    1.600230e+06
0xbaaaf6571ab7d571043ff1e313a9609a10637864    9.401572e+05
0x430f09841d65beb3f27765503d0f850b8bce7713    4.165419e+05
0x513b8629fe877bb581bf244e326a047b249c4ff1    4.035016e+05
0x72c6a4624e1dffa724e6d00d64ceae698af892a0    3.936830e+05
0x75f7eeb85dc639d5e99c78f95393aa9a5f1170d4    3.615766e+05
0x4f93fead39b70a1824f981a54d4e55b278e9f760    3.012879e+05
0x420ab45e0bd8863569a5efbb9c05d91f40624641    1.995056e+05
0x6d6a4b953f202f8df5bed40692e7fd865318264a    1.085186e+05
Name: Closed PnL, dtype: float64

In [39]:
top_coins = merged.groupby(
    'Coin'
)['Closed PnL'].sum().sort_values(
    ascending=False
)

print(top_coins.head(10))

Coin
@107     1.837793e+06
HYPE     1.669186e+06
SOL      9.129941e+05
ETH      8.223682e+05
BTC      5.801358e+05
ZRO      1.854416e+05
DOGE     1.460641e+05
BERA     1.010202e+05
USUAL    6.565969e+04
EIGEN    5.108918e+04
Name: Closed PnL, dtype: float64

In [40]:
merged.groupby(
    ['classification','Side']
)['Closed PnL'].mean()

classification  Side
Extreme Greed   BUY      25.578564
                SELL     25.268770
Fear            BUY     110.309092
                SELL     66.600683
Greed           BUY     -38.222167
                SELL    308.306236
Neutral         BUY      37.435106
                SELL     76.438950
Name: Closed PnL, dtype: float64

In [41]:
import os
print(os.listdir())

['.ipynb_checkpoints', '.virtualenvs', '.vimrc', '.bashrc', 'Untitled.ipynb', '.jupyter', 'fear_greed_index.csv', '.local', 'Untitled1.ipynb', 'anaconda_projects', '.profile', '.pythonstartup.py', 'untitled.py', 'historical_data.csv', 'liner regression.ipynb', 'README.ipynb', '.gitconfig', 'Untitled2.ipynb', '.npm', '.ipython', '.config', '.anaconda', '.cache']

In [42]:
merged.to_csv(
    "merged_trader_sentiment.csv",
    index=False
)

print("File Saved Successfully")

File Saved Successfully

In [43]:
import os

print(os.listdir())

['.ipynb_checkpoints', '.virtualenvs', '.vimrc', '.bashrc', 'Untitled.ipynb', '.jupyter', 'fear_greed_index.csv', '.local', 'Untitled1.ipynb', 'anaconda_projects', '.profile', '.pythonstartup.py', 'untitled.py', 'historical_data.csv', 'liner regression.ipynb', 'README.ipynb', '.gitconfig', 'Untitled2.ipynb', '.npm', '.ipython', '.config', '.anaconda', 'merged_trader_sentiment.csv', '.cache']

In [48]:
merged.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,date,classification,value,Win
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.345404,8.950000e+14,2024-10-27 03:33:20,2024-10-27,Greed,74,False
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.005600,4.430000e+14,2024-10-27 03:33:20,2024-10-27,Greed,74,False
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.050431,6.600000e+14,2024-10-27 03:33:20,2024-10-27,Greed,74,False
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.050043,1.080000e+15,2024-10-27 03:33:20,2024-10-27,Greed,74,False
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,5.201771e+10,True,0.003055,1.050000e+15,2024-10-27 03:33:20,2024-10-27,Greed,74,False

In [49]:
merged.to_csv("merged_trader_sentiment.csv", index=False)

print("Saved")

Saved

In [50]:
import os

print(os.getcwd())

/home/ef6e65df-62fe-4def-b6e2-88db5e7b6923

In [51]:
import os

for file in os.listdir():
    print(file)

.ipynb_checkpoints
.virtualenvs
.vimrc
.bashrc
Untitled.ipynb
.jupyter
fear_greed_index.csv
.local
Untitled1.ipynb
anaconda_projects
.profile
.pythonstartup.py
untitled.py
historical_data.csv
liner regression.ipynb
README.ipynb
.gitconfig
Untitled2.ipynb
.npm
.ipython
.config
.anaconda
merged_trader_sentiment.csv
.cache

In [52]:
merged.shape

(76573, 20)

In [53]:
import os
print(os.getcwd())

/home/ef6e65df-62fe-4def-b6e2-88db5e7b6923